### ISSUE TITLE
BadLocationException: Wrong (offset+length)

### ISSUE THREAD

**Issue by csonuryilmaz** [manticore-projects/jsqlformatter#1]
Hi, I've installed `.nbm` from [here](https://github.com/manticore-projects/jsqlformatter/releases/download/0.1.6/externalcodeformatter-sql.nbm). `0.1.6` I've added a `.sql` file with a query:
```SQL
select * from customer c where date_added >= '2021-04-26 00:00' order by date_added desc limit 3;
```
![2021-05-01_17-03](https://user-images.githubusercontent.com/7355362/116785044-29572b80-aaa0-11eb-92d8-91e1bd75685b.png)

When I try to format, I'm getting _"BadLocationException: Wrong (offset+length)"_ exception without formatting query.

![Screenshot_2021-05-01_17-06-20](https://user-images.githubusercontent.com/7355362/116785055-37a54780-aaa0-11eb-8b2b-689da82e7a69.png)

```
Product Version: Apache NetBeans IDE 12.3
Java: 11.0.11; Java HotSpot(TM) 64-Bit Server VM 11.0.11+9-LTS-194
Runtime: Java(TM) SE Runtime Environment 11.0.11+9-LTS-194
System: Linux version 4.19.0-0.bpo.9-amd64 running on amd64; UTF-8; en_US (nb)
```

**Comment by manticore-projects** [comment]
Onur,

please try to add an Empty Line after the Statement (just one more line
break).
e.g.

> select * from customer c where date_added >= '2021-04-26 00:00' order
> by date_added desc limit 3;
> 

The error is thrown by netbeans, not by my code. So I need a bit time
to understand, why/what is happening there.
Thanks for reporting.

Cheers
Andreas

**Comment by csonuryilmaz** [comment]
Thanks, if I add a new line to file like this ...

![2021-05-01_17-15](https://user-images.githubusercontent.com/7355362/116785213-fcefdf00-aaa0-11eb-8cf5-f3e7c220fa4e.png)

... now formatter works like a charm. :hugs: 

![2021-05-01_17-15_1](https://user-images.githubusercontent.com/7355362/116785245-23ae1580-aaa1-11eb-858e-69c085e63f04.png)

**Comment by manticore-projects** [comment]
Fixed via funfried/externalcodeformatter_for_netbeans/#147

In the meantime, you can download a snapshot NBM from here: https://github.com/manticore-projects/jsqlformatter/releases/download/0.1.6/externalcodeformatter-sql.nbm
