### ISSUE TITLE
How to be compatible with sqls containing keywords

### ISSUE THREAD

**Issue by zhenchuan9r** [manticore-projects/jsqlformatter#12]
It's actually not a problem but a question.
I notice that on the [Online DEMO](http://jsqlformatter.manticore-projects.com/), the following sql is parsable.
```
SELECT operator.c1 AS c1, apply.c2 as c2 from t_test1 operator left join t_test2 apply on operator.c3=apply.c3
```
But when I try it on original JSQLParser, the upper SQL is not parsable, complaining about syntax error.
I would like to ask if you have ever done some optimization on JSQLParser.
Thank you.

**Comment by zhenchuan9r** [comment]
In the above example, `apply` is a keyword.

**Comment by manticore-projects** [comment]
Greetings!

The Online Demo uses a bleeding edge version of JSQLParser including all patches and enhancements we have provided. You can get the same from JSQLParser Source, compiling by yourself.
