### ISSUE TITLE
There is a bug in modifying the table name statement

### ISSUE THREAD

**Issue by reynolds2019** [manticore-projects/jsqlformatter#14]
There is a bug in modifying the table name statement：
```
JSQLFormatter.format("ALTER TABLE TABLE1 RENAME TO TABLE2")
=>
ALTER TABLE table1
    RENAME_TABLE
;
```

**Comment by manticore-projects** [comment]
thank you for reporting, I will look into this asap.

**Comment by manticore-projects** [comment]
Should be fixed in SNAPSHOT, [you can test it online here](http://jsqlformatter.manticore-projects.com/jsqlformatter/demo.html?args=-c%20IIGQKgogSgBGwCEQTo5BGGUIDlgFkUwB5VJCAJiA).

Thank again for reporting.
