### ISSUE TITLE
JSQLFormatter fails with the last JSQLParser SNAPSHOT

### ISSUE THREAD

**Issue by hayssams** [manticore-projects/jsqlformatter#19]
ERROR Main: java.lang.NoSuchMethodError: 'net.sf.jsqlparser.statement.select.Select net.sf.jsqlparser.statement.select.WithItem.getSelect()'

jsqlparser:5.1-SNAPSHOT
jsqlformatter:5.0

**Comment by manticore-projects** [comment]
This has been resolved.
