### ISSUE TITLE
ParseException: Encountered unexpected token:<EOF>

### ISSUE THREAD

**Issue by csonuryilmaz** [manticore-projects/jsqlformatter#2]
When I add (create) a new `.sql` file in Netbeans, 

![2021-05-15_13-08](https://user-images.githubusercontent.com/7355362/118356614-c45f0380-b57e-11eb-921e-a02ce30f9fe5.png)

.. it makes a file with default comment:

![2021-05-15_13-08_1](https://user-images.githubusercontent.com/7355362/118356620-ce810200-b57e-11eb-8682-ecbc0bd0fb6b.png)

IMHO it also triggers auto formatting on new file which generates below exception:
- net.sf.jsqlparser.parser.ParseException: Encountered unexpected token:<EOF> at line 9, column 3

Full exception here :point_right:  [parseException.txt](https://github.com/manticore-projects/jsqlformatter/files/6485528/parseException.txt)

**Comment by manticore-projects** [comment]
Thank you for reporting.
I have implemented an additional check and avoid throwing any exception, when the Total Trimmed Statement Length <= Total Comment Length (which means, there are only comments but no actual SQL code).

**Comment by manticore-projects** [comment]
You can get a fixed Netbeans Plugin from here: https://github.com/manticore-projects/jsqlformatter/releases/download/0.1.7-PRE/externalcodeformatter-1.14.1-SNAPSHOT.zip

**Comment by csonuryilmaz** [comment]
Thanks, I've tested w/ latest `.nbm` that you shared. Fixed. :heavy_check_mark:

**Comment by manticore-projects** [comment]
You are most welcome.
If anything else comes up, just drop the SQL statement which fails to
format. In the most cases I will figure out the problem even without
any additional description. Will save you some time and effort.

Cheers and thank you again for testing and reporting.
