### ISSUE TITLE
missing "limit" keyword after format

### ISSUE THREAD

**Issue by csonuryilmaz** [manticore-projects/jsqlformatter#3]
I tried to format below SQL query.

![2021-05-15_13-15](https://user-images.githubusercontent.com/7355362/118356879-f4f36d00-b57f-11eb-9520-682ca0b8e797.png)

Formatter beautified the query without any error or exception.

![2021-05-15_13-16](https://user-images.githubusercontent.com/7355362/118356953-44399d80-b580-11eb-8647-bc6016d44b56.png)

**But** formatted SQL didn't contain `LIMIT 200000 ` part of the string.

In order to reproduce case easily, I'm pasting raw SQL query as a text below:
```sql
SELECT p.* 
FROM product p 
LEFT JOIN product_description pd ON (p.product_id = pd.product_id) 
LEFT JOIN product_type_google_category ptgc ON (p.product_type_id = ptgc.product_type_id) 
LEFT JOIN product_google_custom_label pgcl ON (p.product_id = pgcl.product_id) 
WHERE p.status=1 AND pd.language_id = 2 
AND p.product_id IN (SELECT product_id FROM cj_googleshopping_products) 
 ORDER BY date_available DESC, p.purchased DESC LIMIT 200000 
```
---
**Note:** Forgot to mention that I'm using MySQL and MySQL supports the `LIMIT` clause to select a limited number of records. See [here](https://www.w3schools.com/sql/sql_top.asp) for other keywords used by various databases to provide the same functionality.

**Comment by manticore-projects** [comment]
Thank you so much for reporting. It is true, I left out a few fragments yet (especially when I never have used them myself).
I just committed a fix in JSQLFormatter, you can [test it here interactively](http://217.160.215.75:8080/jsqlformatter/demo.html?args=-c%20MoUQMiDCAqAEAOA6AVAKAGICUDyBZBATgPYAmArgMYAuCqs9sE6cAUtgJIByhplVA+iQCmAZwoEAlvCoSiAOwQk6DFdm4AKBInjFy1fhJKwAvIu26+BowEpl9Jqw7cdvfVQCe8IfwDmRIj4ANt4UAIZUQn4E7ghUPhR2KrBqsJpILnoCHl5WJrHx5q5Znt6GsLYqDrBsXDyZvv5BIWQiVEQAtvyBoQBGQoEI8YGJqhpaGZZlpvBDhfVltgDqABIgmCBareEteQCMiQCCnAAiZt1yPmShPqVGpgBMhyfjFvpltZr0oBAwdZNKSUBQOB9CweFgFAAVg0AsERAALIjweASC78CbUETlVDYTDHNawABCAE0VCRwt5QgA3UISbo9YKwfHASAjIEAGnGZAIFHhoREQiMzNZYHYuHYcHuAAYZTLUABuIA+)

**Comment by manticore-projects** [comment]
You can get a fixed Netbeans Plugin from here: https://github.com/manticore-projects/jsqlformatter/releases/download/0.1.7-PRE/externalcodeformatter-1.14.1-SNAPSHOT.zip

**Comment by csonuryilmaz** [comment]
Thanks, I've installed latest `.nbm` that you shared. It works fine now. :hugs:

Fixed. :heavy_check_mark:
